### ISSUE TITLE
Copy vendor dir to speed up composer install

### ISSUE THREAD

**Issue by rommsen** [f500/ansible-project_deploy#11]
Hi there,

first of all, great role. Helps me a ton.

I would like to be able to speed up my composer install by copying the vendor dir from the old release (like: http://capifony.org/cookbook/speeding-up-deploy.html). 

I was not able to put the cp command in project_pre_build_commands because this will break on the first deployment when current/vendor is not available yet. 

Currently I am patching the role with the following tasks:
```yaml
- name: Check if vendor dir exists
  stat: path={{ project_root }}/current/vendor
  register: check_vendor_path

- name: Copy vendor dir if exists to speed up composer
  command: /bin/cp -rp {{ project_root }}/current/vendor {{ deploy_helper.new_release_path }}
  when: check_vendor_path.stat.exists
```
It speeds up the deployment process quite drastically. 

What do you think? Worth a PR? Any other solutions.

Cheers
